version: 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/ci # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/python:3.8.0
    steps: # a collection of executable commands
      - checkout # special step to check out source code to the working directory
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $suguruyaginuma/regression_em:latest .
      - run: # install and activate virtual environment with pip
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt -r requirements-dev.txt
      - run: # run tests
          name: Run tests
          command: |
            pytest tests/
          no_output_timeout: 15m
      - store_artifacts: # special step to store test reports as artifacts
          path: test-reports/
          destination: tr1
      - run:
          name: Build documents
          command: |
            sphinx-build -a ./docs/ ./docs/html/;
            tar cfvz html.tar.gz docs/html/
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
          requires:
            - build
          filters:
            branches:
              only: develop